apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-spring-k8s-demo-cpu
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: main-spring-k8s-demo
  targetCPUUtilizationPercentage: 50
