apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: three-routing
spec:
  hosts:
    - three-spring-k8s-demo
  http:
    - route:
      - destination:
          host: two-spring-k8s-demo
        weight: 50
      - destination:
          host: one-spring-k8s-demo
        weight: 50