apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: one-with-timeout
spec:
  hosts:
  - two-spring-k8s-demo
  http:
  - route:
    - destination:
        host: two-spring-k8s-demo
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx