apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: one-with-timeout
spec:
  hosts:
  - one-spring-k8s-demo
  http:
  - route:
    - destination:
        host: one-spring-k8s-demo
    timeout: 0.5s