apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "spring-k8s-demo.fullname" . }}
  labels:
    app: {{ include "spring-k8s-demo.name" . }}
    chart: {{ include "spring-k8s-demo.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "spring-k8s-demo.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
      labels:
        app: {{ include "spring-k8s-demo.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          - name: REMOTE_SERVICES
            value: '{{- join "," .Values.remote.services -}}'
          - name: JAVA_OPTS
            value: "-Dopentracing.jaeger.enabled=true -Dopentracing.jaeger.serviceName={{ .Release.Name }} -Dopentracing.jaeger.udp-sender.host=jaeger-agent.kube-system -Dopentracing.jaeger.udp-sender.port=6831 -Dopentracing.jaeger.probabilistic-sampler.sampling-rate=1.0"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
